[package]
name = "rth"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35", features = ["full"] }
tokio-cron-scheduler = "0.14.0"
chrono = { version = "0.4", default-features = false }
